package q1;

import java.util.Random;

public abstract class Student {
    private String firstName;
    private String lastName;
    private Year year;
    private String studentId;
    private int yearOfGraduation;
    private String department;
    private double courseFee;
    private double semesterFee;

    public Student() {
    }

    public Student(String firstName, String lastName, Year year, int yearOfGraduation, String department, double courseFee) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.year = year;
        this.yearOfGraduation = yearOfGraduation;
        this.department = department;
        this.courseFee = courseFee;
        this.studentId = this.generateId(); // student Id is automatically generated by the system
        this.semesterFee = this.calculateSemesterFee();
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Year getYear() {
        return year;
    }

    public void setYear(Year year) {
        this.year = year;
    }

    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public int getYearOfGraduation() {
        return yearOfGraduation;
    }

    public void setYearOfGraduation(int yearOfGraduation) {
        this.yearOfGraduation = yearOfGraduation;
    }

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public double getCourseFee() {
        return courseFee;
    }

    public void setCourseFee(double courseFee) {
        this.courseFee = courseFee;
    }

    public double getSemesterFee() {
        return semesterFee;
    }

    public void setSemesterFee(double semesterFee) {
        this.semesterFee = semesterFee;
    }

    public String generateId() {
        StringBuilder builder = new StringBuilder();
        Random r = new Random();
        builder.append(firstName.toUpperCase().charAt(0)).append(lastName.toUpperCase().charAt(0)).append('-');
        for (int i = 0; i < 4; i++) {
            builder.append(r.nextInt(10));
        }

        return builder.toString();

    }

    public abstract String toString();

    public abstract double calculateSemesterFee();

    public abstract boolean isExceedingFiveClasses();
}
